version: '3'
services:
  web:
    image: php:apache
    ports:
      - "80:80"
    volumes:
      - C:\Users\marciopc\Documents\ProjetosMeuPC\Docker-MySQL\mysteam-docker-mysql:/var/www/html
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: mysteam
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
